### ISSUE TITLE
Issue installing cronjob

### ISSUE THREAD

**Issue by Gwyll** [centosadmin/redmine_activity_report#21]
Executing  bundle exec whenever -i redmine_activity_report -f plugins/redmine_activity_report/config/schedule.rb from the redmine root directory produces this error:

/usr/local/rvm/gems/ruby-2.4.1/gems/whenever-0.10.0/lib/whenever/command_line.rb:119:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/whenever-0.10.0/lib/whenever/command_line.rb:119:in `prepare'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/whenever-0.10.0/lib/whenever/command_line.rb:68:in `read_crontab'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/whenever-0.10.0/lib/whenever/command_line.rb:97:in `updated_crontab'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/whenever-0.10.0/lib/whenever/command_line.rb:38:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/whenever-0.10.0/lib/whenever/command_line.rb:6:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/whenever-0.10.0/bin/whenever:44:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/whenever:23:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/whenever:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

It is a fresh redmine install. What did I miss?

Thanks

**Comment by kmarkovych** [comment]
This works wor me:
`echo gem \"whenever\" > plugins/redmine_activity_report/Gemfile`
and then
`bundle install`

**Comment by Gwyll** [comment]
Thank you ... unfortunately I am unable to test your solution.
