### ISSUE TITLE
Error in Redmine 4.0.4

### ISSUE THREAD

**Issue by koren85** [centosadmin/redmine_activity_report#26]
I got this errors on execute commands in Redmine 4.0.4 Docker version
command:
`RAILS_ENV=production bundle exec rake activity_report:monthly --trace`

```
root@03b0c83d65c0:/home/redmine/redmine# RAILS_ENV=production bundle exec rake activity_report:monthly --trace
** Invoke activity_report:monthly (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute activity_report:monthly
rake aborted!
ActionView::Template::Error: undefined method `default_url_options' for ActionMailer::Parameterized::Mailer:Class
/home/redmine/redmine/plugins/redmine_activity_report/app/models/activity_report_mailer.rb:11:in `default_url_options'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/class/attribute.rb:128:in `public_send'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/class/attribute.rb:128:in `block (2 levels) in class_attribute'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/url_for.rb:219:in `optimize_routes_generation?'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/routing_url_for.rb:134:in `optimize_routes_generation?'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:229:in `optimize_routes_generation?'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:199:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:331:in `block (2 levels) in define_url_helper'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:29:in `block (2 levels) in _97e9ef89c4627687adbc01a38e28fc97'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:25:in `each'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:25:in `block in _97e9ef89c4627687adbc01a38e28fc97'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:9:in `each'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:9:in `_97e9ef89c4627687adbc01a38e28fc97'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:159:in `block in render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:354:in `instrument_render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:157:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/deface-1.3.2/lib/deface/action_view_extensions.rb:41:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:16:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:44:in `render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:25:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:103:in `_render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:84:in `render_to_body'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/rendering.rb:25:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:943:in `block in collect_responses_from_templates'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `map'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `collect_responses_from_templates'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:925:in `collect_responses'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:828:in `mail'
/home/redmine/redmine/plugins/redmine_activity_report/app/models/activity_report_mailer.rb:28:in `report'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:25:in `block in process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:24:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:607:in `block in process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:606:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:122:in `tap'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/home/redmine/redmine/plugins/redmine_activity_report/lib/activity_report.rb:49:in `block in send_activity_reports'
/home/redmine/redmine/plugins/redmine_activity_report/lib/activity_report.rb:48:in `each'
/home/redmine/redmine/plugins/redmine_activity_report/lib/activity_report.rb:48:in `send_activity_reports'
/home/redmine/redmine/plugins/redmine_activity_report/lib/tasks/activity_report.rake:9:in `block (2 levels) in <top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<main>'

Caused by:
NoMethodError: undefined method `default_url_options' for ActionMailer::Parameterized::Mailer:Class
/home/redmine/redmine/plugins/redmine_activity_report/app/models/activity_report_mailer.rb:11:in `default_url_options'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/class/attribute.rb:128:in `public_send'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/class/attribute.rb:128:in `block (2 levels) in class_attribute'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/url_for.rb:219:in `optimize_routes_generation?'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/routing_url_for.rb:134:in `optimize_routes_generation?'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:229:in `optimize_routes_generation?'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:199:in `call'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:331:in `block (2 levels) in define_url_helper'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:29:in `block (2 levels) in _97e9ef89c4627687adbc01a38e28fc97'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:25:in `each'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:25:in `block in _97e9ef89c4627687adbc01a38e28fc97'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:9:in `each'
/home/redmine/redmine/plugins/redmine_activity_report/app/views/activity_report_mailer/report.html.erb:9:in `_97e9ef89c4627687adbc01a38e28fc97'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:159:in `block in render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:354:in `instrument_render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:157:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/deface-1.3.2/lib/deface/action_view_extensions.rb:41:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:16:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:44:in `render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:25:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:103:in `_render_template'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:84:in `render_to_body'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/rendering.rb:25:in `render'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:943:in `block in collect_responses_from_templates'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `map'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:940:in `collect_responses_from_templates'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:925:in `collect_responses'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:828:in `mail'
/home/redmine/redmine/plugins/redmine_activity_report/app/models/activity_report_mailer.rb:28:in `report'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:25:in `block in process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:24:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:607:in `block in process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:606:in `process'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:122:in `tap'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/home/redmine/redmine/plugins/redmine_activity_report/lib/activity_report.rb:49:in `block in send_activity_reports'
/home/redmine/redmine/plugins/redmine_activity_report/lib/activity_report.rb:48:in `each'
/home/redmine/redmine/plugins/redmine_activity_report/lib/activity_report.rb:48:in `send_activity_reports'
/home/redmine/redmine/plugins/redmine_activity_report/lib/tasks/activity_report.rake:9:in `block (2 levels) in <top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<main>'
Tasks: TOP => activity_report:monthly
```

what should i do to fix the error?

**Comment by koren85** [comment]
I fix error.
in /plugins/redmine_activity_report/app/models/activity_report_mailer.rb

set:

```
  def self.default_url_options
    #Mailer.default_url_options
    ::Mailer.default_url_options
  end
```
thank's for plugin! very useful!
